// STATO SEMAFORO ROSSO ERRORI INVERTER 1PH 1100TL-3300TL-V3

// ID01 - LA TENSIONE DI RETE E' TROPPO ALTA
//ID02 - LA TENSIONE DI RETE E' TROPPO BASSA
//ID03 - LA FREQUENZA DI RETE E' TROPPO ALTA
//ID04 - LA FREQUENZA DI RETE E' TROPPO BASSA
//ID05 - LA TENSIONE DI INGRESSO E' TROPPO BASSA
//ID06 - ERRORE FUNZIONE LVRT
//ID07 - ERRORE FUNZIONE OVRT
//ID09 - LA TENSIONE DI INGRESSO E' TROPPO ALTA
//ID10 - LA CORRENTE IN INGRESSO E' SQUILIBRATA
//ID11 - MODALITA' DI INGRESSO SCORRETTA
//ID12 - GUASTO DELL'INTERRUTORE AUTOMATICO DIFFERENZIALE
//ID14 - LA CORRENTE DI INGRESSO E' TROPPO ALTA E HA CAUSATO L'ATTIVAZIONE DELLA PROTEZIONE HARDWARE
//ID15 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO L'ATTIVAZIONE DELLA PROTEZIONE HARDWARE
//ID16 - LA CORRENTE DI RETE E' TROPPO ALTA
//ID17 - ERRORE NEL CAMPIONAMENTO DELLA CORRENTE DI RETE
//ID18 - ERRORE CAMPIONAMENTO DCI
//ID19 - ERRORE NEL CAMPIONAMENTO DELLA TENSIONE DI RETE
//ID20 - ERRORE NEL CAMPIONAMENTO GFCI
//ID21 - IL MASTER CHIP PRESENTA UN ERRORE
//ID22 - ERRORE DELLA TENSIONE AUSILIARE
//ID23 - ERRORE NEL CAMPIONAMENTO DELLA TENSIONE DI BUS
//ID24 - LA CORRENTE IN USCITA NON E' BILANCIATA
//ID25 - LA TENBSIONE DEL BUS E' TROPPO BASSA
//ID26 - LA TENSIONE DEL BUS E' TROPPO ALTA
//ID27 - LA TENSIONE DEL BUS NON E' BILANCIATA
//ID28 - LA DCI E' TROPPO ALTA
//ID29 - LA CORRENTE DI RETE E' TROPPO ALTA
//ID30 - LA CORRENTE DI INGRESSO E' TROPPO ALTA
//ID33 - RISERVATO (CONTATTARE PRODUTTORI)
//ID49 - IL VALORE DELLA CAMPIONATURA DELLA TENSIONE DI RETE TRA IL DSP MASTER E IL DSP SLAVE NON E UGUALE
//ID50 - IL VALORE DI CAMPIONATURA DELLA FREQUENZA DI RETE TRA IL DSP MASTER E IL DSP SLAVE NON E' UGUALE.
//ID51 - IL VALORE DI CAMPIONATURA DELLA CORRENTE DELL'INTERRUTORE AUTOMATICO.
//ID52 - IL VALORE DI CAMPIONATURA DELLA CORRENTE DELL'INTERRUTORE AUTOMATICO DIFFERENZIALE (GFCI) TRA IL DSP MASTER E IL DSP SLAVE NON E' UGUALE
//ID53 - ERRORE DI COMUNICAZIONE SPI TRA IL DSP MASTER E IL DSP SLAVE
//ID54 - ERRORE DI COMUNICAZIONE SCI TRA IL DSP MASTER E IL DSP SLAVE
//ID55 - RELE'GUASTO
//ID56 - LA RESISTENZA DI ISOLAMENTO E' TROPPO BASSA
//ID57 - LA TEMPERATURA DELL'INVERTER E' TROPPO ALTA
//ID58 - LA TEMPERATURA DEL BOOST E' TROPPO ALTA
//ID59 - LA TEMPERATURA AMBIENTE E' TROPPO ALTA
//ID65 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO UN GUASTO HARDWARE IRREVERSIBILE
//ID66 - LA TENSIONE DEL BUS E' TROPPO ALTA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID67 - LA CORRENTE DI RETE E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID68 - LA CORRENTE DI INGRESSO E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID69 - LA TENSIONE DEL BUS E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID70 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID71 - MODALITA' DI INGRESSO SCORRETTA
//ID74 - LA CORRENTE DI INGRESSO E' TROPPO ALTA ED HA CAUSATO UN GUASTO IRRIMEDIABILE
//ID75 - LA EEPROM E' IRRECUPERABILE
//ID76 - LA EEPROM E' IRRECUPERABILE
//ID77 - IL RELE' HA GENERATO UN GUASTO PERMANENTE
//ID81 - DERATING A CAUSA DI TEMPERATURA TROPPO ALTA
//ID82 - L'INVERTER E' STATO DEPOTENZIATO A CAUSA DELLA FREQUENZA DI RETE TROPPO ALTA
//ID83 - L'INVERTER E' STATO DEPOTENZIATO ATTRAVERSO IL CONTROLLO REMOTO
//ID84 - L'INVERTER E' STATO SPENTO ATTRAVERSO IL CONTROLLO REMOTO
//ID85 - L'INVERTER E' STATO DEPOTENZIATO A CAUSA DI CORRENTE DI RETE TROPPO BASSA
//ID89 - RISERVATO (CONTATTARE PRODUTTORI)
//ID93 - ATTIVAZIONE PROTEZIONE SOVRATENSIONI CAUSATE DA FULMINI
//ID94 - IL SOFTWARE DELLA SCHEDA DI CONTROLLO E DELLA SCHEDA DI COMUNICAZIONE NON CORRISPONDE
//ID95 - LA SCHEDA DI COMUNICAZIONE EEPROM E' GUASTA
//ID96 - IL CHIP DELL'OROLOGIO RTC E' GUASTO
//ID97 - IL PAESE SELEZIONATO NON E' VALIDO
//ID98 - LA SCHEDA SD E' GUASTA
//ID99-ID100 - RISERVATO (CONTATTARE PRODUTTORI)


//STATO SEMAFORO ROSSO ERRORI INVERTER 3PH HYD5000-HYD12000 ZP3

//ID01 - LA TENSIONE DELLA RETE DI ALIMENTAZIONE E' TROPPO ELEVATA
//ID02 - LA TENSIONE DI RETE E' TROPPO BASSA
//ID03 - LA FREQUENZA DI RETE E' ECCESSIVA
//ID04 - LA FREQUENZA DI RETE E' INSUFFICIENTE
//ID05 - ERRORE DISPERSIONE DI CARICA
//ID08 - ERRORE PROTEZIONE ISLAND
//ID09 - SOVRATENSIONE TRANSITORIA DELLA TENSIONE 1
//ID10 - SOVRATENSIONE TRANSITORIA DELLA TENSIONE 2
//ID11 - ERRORE DI TENSIONE DELLA LINEA DI ALIMENTAZIONE DI RETE
//ID12 - SOVRATENSIONE INVERTER
//ID13 - LA FUNZIONE LIMITE DI IMMISSIONE NON FUNZIONA
//ID32 - ERRORE DI MESSA A TERRA DEL NEUTRO
//ID33 - ERRORE DI COMUNICAZIONE SPI (DC)
//ID34 - ERRORE DI COMUNICAZIONE SPI (AC)
//ID38 - L'INVERTER NON GENERA NULLA
//ID39 - PROEZIONE SPEGNIMENTO ARCO
//ID40 - RILEVAMENTO LUCE BASSA NON RIUSCITO
//ID41 - ERRORE RILEVAZIONE RELE'
//ID42 - RESISTENZA DI ISOLAMENTO TROPPO BASSA
//ID43 - ERRORE DI MESSA TERRA 
//ID44 - CONFIGURAZIONE MODALITA' DI INGRESSO NON CORRETTA
//ID45 - ERRORE CT
//ID46 - IL PV E' COLLEGATO AL CONTRARIO 
//ID47 - NON E' PRESENTE UN MASTER O E' DUPLICATO
//ID49 - ERRORE DELLA TEMPERATURA DELLA BATTERIA
//ID50 - ERRORE TEMPERATURA DEL DISSAPATORE DI CALORE 1
//ID51 - ERRORE TEMPERATURA DEL DISSAPTORE DI CALORE 2
//ID52 - ERRORE TEMPERATURA DEL DISSAPTORE DI CALORE 3
//ID53 - ERRORE TEMPERATURA DEL DISSAPTORE DI CALORE 4
//ID54 - ERRORE TEMPERATURA DEL DISSAPTORE DI CALORE 5
//ID55 - ERRORE TEMPERATURA DEL DISSAPTORE DI CALORE 6
//ID57 - ERRORE TEMPERATURA - TEMPERATURA AMBIENTALE 1
//ID58 - ERRORE TEMPERATURA - TEMPERATURA AMBIENTALE 2
//ID59 - MODULO 1 PROTEZIONE TEMPERATURA
//ID60 - MODULO 2 PROTEZIONE TEMPERATURA
//ID61 - MODULO 3 PROTEZIONE TEMPERATURA
//ID65 - RMS TENSIONE DEL BUS NON BILANCIATO
//ID66 - VALORE TRANSITORIO DELLA TENSIONE DEL BUS NON BILANCIATO
//ID67 - LA TENSIONE DEL BUS CC E' TROPPO BASSA DURANTE L'ALLACIAMENTO ALLA RETE
//ID68 - LA TENSIONE DEL BUS CC E' TROPPO BASSA
//ID69 - LA TENSIONE DI INGRESSO PV E' TROPPO ELEVATA
//ID70 - SOVRATENSIONE DELLA BATTERIA
//ID71 - PROTEZIONE DA SOVRATENSIONE BUS LLC
//ID72 - SOVRATENSIONE DEL SOFTWARE RMS DI TENSIONE DEL BUS RMS DELL'INVERTER
//ID73 - SOVRATENSIONE DEL SOFTWARE ISTANTANEO DELLA TENSIONE DEL BUS DELL'INVERTER
//ID81 - PROTEZIONE DA SOVRACORRENTE SOFTWARE DELLA BATTERIA
//ID82 - PROTEZIONE SOVRACORRENTE DCI
//ID83 - PROTEZIONE CORRENTE IN USCITA ISTANTANEA
//ID85 - PROTEZIONE CORRENTE RMS DI USCITA
//ID86 - PROEZIONE SOFTWARE SOVRACORRENTE PV
//ID87 - FLUSSI PV PARALLELE ASIMMETRICHE
//ID88 - CORRENTE IN USCITA NON BILANCIATA
//ID89 - PROTEZIONE DA SOVRACORRENTE SOFTWARE PV
//ID90 - PROTEZIONE DELLA CORRENTE BILANCIATA
//ID98 - SOVRATENSIONE HARDWARE BUS INVERTER
//ID100 - FLUSSO ECCESSIVO HARDWARE BATTERIA
//ID102 - FLUSSI ECCESSIVI HARDWARE PV
//ID103 - LA CORRENTE DELLA RETE PRINCIPALE E' TROPPO ELEVATA E HA FATTO SCATTARE LA PROTEZIONE DELL'HARDWARE
//ID105 - ERRORE DI COMUNICAZIONE CON L'UNITA' CONTATORE
//ID110 - PROTEZIONE SOVRACCARICO 1
//ID111 - PROTEZIONE SOVRACCARICO 2
//ID112 - PROTEZIONE SOVRACCARICO 3
//ID113 -  l'INVERTER SI E' INGOLFATO A CAUSA DI UNA TEMPERATURA TROPPO ELEVATA
//ID114 - LA FREQUENZA CA E' TROPPO ELEVATA
//ID124 - LA BATTERIA E' SCARICA
//ID125 - NESSUNA PROTEZIONE DELLA BATTERIA
//ID128 - LA BATTERIA E' COLLEGATA AL CONTRARIO
//ID129 - LA CORRENTE DELLA RETE PRINCIPALE E' TROPPO ELEVATA E HA CAUSATO UN ERRORE DELL'HARDWARE IRRIMEDIABILE
//ID145 - IL DISPOSITIVO NON E' IN GRADO DI LEGGERE DATI DALLA CHIAVETTA USB. LA CHIAVETTA USB E' STATA DANNEGGIATA. OPPURE IL FORMATO DELLA CHIAVETTA USB NON E' COMPATIBILE CON IL DISPOSITIVO
//ID147 - LA COMUNICAZIONE BLEUTOOTH DEL DISPOSITIVO NON HA FUNZIONATO
//ID151 - UNA PARTE DELLA COMUNICAZIONE DELLA BATTERIA E' PERDUTA
//ID152 - LA VERSIONE DELLA SICUREZZA NON CORRISPONDE ALLA VERSIONE DELLA SICUREZZA INTERNA
//ID153 - ERRORE COMUNICAZIONE SCI (DC)
//ID154 - ERRORE COMUNICAZIONE SCI (AC)
//ID156 - VERSIONI DEL SOFTWARE INCOERENTE
//ID157 - ERRORE DI COMUNICAZIONE 1 DELLA BATTERIA AL LITIO
//ID158 - ERRORE DI COMUNICAZIONE 2 DELLA BATTERIA AL LITIO
//ID162 - SPEGNIMENTO REMOTO
//ID163 - SPEGNIMENTO DRM 0
//ID169 - VENTOLA 1
//ID177 - ALLARME SOVRATENSIONE BMS
//ID178 - ALLARME SOTTOTENSIONE BMS
//ID179 - AVVERTENZA TEMPERATURA ELEVATA BMS 
//ID180 - AVVERTENZA TEMPERATURA BASSA BMS
//ID181 - AVVERTENZA SOVRACCARICO BMS DURANTE LA CARICA E SCARICA
//ID182 - ALLARME CORTOCIRCUITO BMS
//ID183 - VERSIONI DEL SOFTWARE INCOERENTE
//ID184 - VERSIONI DEL SOFTWARE INCOERENTE
//ID185 - VERSIONI DEL SOFTWARE INCOERENTE

//ERRORI BATTERIA

//ID808 - ALLARME TEMPERATURA ELEVATA RADIATORE 1
//ID809 - ALLARME TEMPERATURA ELEVATA AMBIENTALE
//ID813 - ALLARME DIVIETO DI RICARICA
//ID814 - ALLARME DIVIETO DI SCARICA
//ID864 - PROTEZIONE DALLA SOVRATEMPERATURA DEL RADIATORE 1
//ID865 - PROTEZIONE DALLA SOVRATEMPERATURA DELLA TEMPERATURA AMBIENTALE
//ID866 - GUASTO DI COMUNICAZIONE INTERNA DELLA BATTERIA
//ID867 - ERRORE DI COMUNICAZIONE CAN1
//ID872 - SOVRATENSIONE SOFTWARE DEL BUS
//ID873 - SOTTOTENSIONE SOFTWARE DEL BUS
//ID874 - SOVRATENSIONE SOFTWARE DELLA BATTERIA
//ID875 - SOTTOTENSIONE SOFTWARE DELLA BATTERIA
//ID879 - SOVRACORRENTE HARDWARE
//ID880 - SOVRATENSIONE DEL BUS PERMANENTE
//ID883 - SOVRACORRENTE PERMANENTE HARDWARE
//ID893 - PROTEZIONE DEL CORTOCIRCUITO PERMANENTE
//ID894 - ATTIVAZIONE BATTERIA NON RIUSCITA PERMANENTE
//ID895 - COLLEGAMENTO INVERSO BUS PERMANENTE
//ID899 - GUASTO DI SOVRATENSIONE E SOVRACORRENTE BMS
//ID900 - PROTEZIONE DA SOVRACORRENTE MEDIA DELLA BATTERIA
//ID901 - PROTEZIONE DA SOVRACCARICO MEDIA
//ID902 - SOVRACORRENTE SOFTWARE
//ID903 - PROTEZIONE DA SOVRACORRENTE CBC SOFTWARE
//ID905 - PROTEZIONE DAL CORTOCIRCUITO ALL'AVVIO
//ID906 - SOTTOTENSIONE MEDIA DEL BUS
//ID907 - GUASTO ORARIO DEL CHIP
//ID908 - GUASTO COMUNICAZIONE CAN TRA BATTERIA E INVERTER
//ID909 - ERRORE BASSA TEMPERATURA DEL DISSIPATORE DI CALORE
//ID910 - ERRORE BATTERIA BASSA TEMPERATURA AMBIENTALE 
//ID911 - ERRORE CALIBRAZIONE OFFSET CAMPIONE


//STATO SEMAFORO ROSSO ERRORI INVERTER 1PH HYD3000-HYD6000 ZSS

//ID01 - LA TENSIONE DI RETE E' TROPPO ALTA
//ID02 - LA TENSIONE DI RETE E' TROPPO BASSA
//ID03 - LA FREQUENZA DI RETE E' TROPPO ALTA
//ID04 - LA FREQUENZA DI RETE E' TROPPO BASSA
//ID05 - LA TENSIONE DELLA BATTERIA E' TROPPO ELEVATA
//ID06 - ERRORE FUNZIONE LVRT
//ID07 - ERRORE FUNZIONE OVRT
//ID08 - LA TENSIONE DEL FOTOVOLTAICO E' TROPPO ELEVATA
//ID09 - LA TENSIONE DEL LLCBUS E' TROPPO ELEVATA E HA INNESCATO LA PROTEZIOJNE HARDWARE
//ID10 - L'AUMENTO DI TENSIONE E' TROPPO ALTA E' HA INNESCATO LA PROTEZIONE HARDWARE
//ID11 - LA CORRENTE BUCKBOOST E' TROPPO ALTA E HA INNESCATO LA PROTEZIONE HARDWARE
//ID12 - LA CORRENTE DELLA BATTERIA E' TROPPO ALTA E HA INNESCATO LA PROTEZIONE HARDWARE
//ID13 - IL VALORE DI CAMPIONATURA GFCI FRA IL DSP MASTER E IL DSP SLAVE NON E' ADEGUATO
//ID14 - LA CORRENTE FOTOVOLTAICA E' TROPPO ALTA E HA INNESCATO LA PROTEZIONE HARDWARE
//ID15 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO L'ATTIVAZIONE DELLA PROTEZIONE HARDWARE
//ID16 - LA CORRENTE DI INGRESSO NON E' BILANCIATA
//ID17 - ERRORE NEL CAMPIONAMENTO DELLA CORRENTE DI RETE
//ID18 - ERRORE CAMPIONAMENTO DCI
//ID19 - ERRORE NEL CAMPIONAMENTO DELLA TENSIONE DI RETE
//ID20 - ERRORE NEL CAMPIONAMENTO GFCI
//ID21 - IL MASTER CHIP PRESENTA UN ERRORE
//ID22 - ERRORE DELLA TENSIONE AUSILIARE
//ID23 - ERRORE NEL CAMPIONAMENTO DELLA TENSIONE DI BUS
//ID24 - LA CORRENTE IN USCITA NON E' BILANCIATA
//ID25 - LA TENBSIONE DEL LLCBUS E' TROPPO BASSA
//ID26 - LA TENSIONE DEL BUS E' TROPPO ALTA E HA INNESCATO LA PROTEZIONE HARDWARE
//ID27 - CORRENTE DI BATTERIA E' TROPPO ALTO
//ID28 - LA DCI E' TROPPO ALTA
//ID29 - LA CORRENTE DI RETE E' TROPPO ALTA
//ID30 - LA CORRENTE BULCK E' TROPPO ALTA
//ID31 - LA CORRENTE IN USCITA E' TROPPO ALTA
//ID32 - LA CORRENTE IN INGRESSO E' TROPPO ALTA
//ID33 - MODO INGRESSO SCORRETTO
//ID34 - SOVRACCARICO
//ID35 - IL CT E' GUASTO
//ID48 - IL VALORE DI CAMPIONATURA GFCI FRA IL DSP MASTER E IL SLAVE NON E' ADEGUATO
//ID49 - IL VALORE DELLA CAMPIONATURA DELLA TENSIONE DI RETE TRA IL DSP MASTER E IL DSP SLAVE NON E UGUALE
//ID50 - IL VALORE DI CAMPIONATURA DELLA FREQUENZA DI RETE TRA IL DSP MASTER E IL DSP SLAVE NON E' UGUALE.
//ID51 - IL VALORE DI CAMPIONAMENTO DCI TRA IL DSP MASTER E IL DSP SLAVE NON È COERENTE
//ID52 - L'INVERTER HYD-ES NON RIESCE A COMUNICARE CORRETTAMENTE CON IL BMS DELLA BATTERIA AL LITIO
//ID53 - ERRORE DI COMUNICAZIONE SPI TRA IL DSP MASTER E IL DSP SLAVE
//ID54 - ERRORE DI COMUNICAZIONE SCI TRA IL DSP MASTER E IL DSP SLAVE
//ID55 - RELE'GUASTO
//ID56 - LA RESISTENZA DI ISOLAMENTO E' TROPPO BASSA
//ID57 - LA TEMPERATURA DELLA ATTERIA E' TROPPO ALTA
//ID58 - LA TEMPERATURA DEL DISSIPATORE E' TROPPO ELEVATA
//ID59 - LA TEMPERATURA AMBIENTE E' TROPPO ALTA
//ID60 - CONTROLLARE LA MESSA A TERRA
//ID65 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO UN GUASTO HARDWARE IRREVERSIBILE
//ID66 - LA TENSIONE DEL BUS E' TROPPO ALTA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID67 - GUASTO IRRIMEDIABILE SOVRACORRENTE BATTERIA IN MODALITA' EPS
//ID68 - LA CORRENTE DI INGRESSO E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID69 - LA TENSIONE DEL BUS E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID70 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID73 - LA CORRENTE DI INGRESSO E' TROPPO ALTA E HA CAUSATO UN GUASTO IRRIMEDIABILE
//ID74 - MODO INGRESSO INCORRETTO
//ID75 - LA SCRITTURA EEPROM E' IRRECUPERABILE
//ID76 - LA LETTURA EEPROM E' IRRECUPERABILE
//ID77 - IL RELE' HA GENERATO UN GUASTO PERMANENTE
//ID81 - LA TEMPERATURA INTERNA E' TROPPO ELEVATA
//ID82 - FREQUENZA AC E' TROPPO ELEVATA
//ID83 - DECLASSAMENTO POTENZA REMOTA
//ID84 - L'INVERTER E' STATO SPENTO ATTRAVERSO IL CONTROLLO REMOTO
//ID85 - TENSIONE DELLA BATTERIA INFERIORE A SOC
//ID86 - CARICA FORZATA FALLITA
//ID94 - IL SOFTWARE DELLA SCHEDA DI CONTROLLO E DELLA SCHEDA DI COMUNICAZIONE NON CORRISPONDE
//ID95 - LA SCHEDA DI COMUNICAZIONE EEPROM E' GUASTA
//ID96 - IL CHIP DELL'OROLOGIO RTC E' GUASTO
//ID97 - IL PAESE SELEZIONATO NON E' VALIDO
//ID98 - LA SCHEDA SD E' GUASTA
//ID99 - IL WIFI E' IN ERRORE
//ID100 - PROTEZIONE DA SOVRACORRENTE DI SCARICA DELLA BATTERIA 
//ID101 - PROTEZIONE SCARICA CORTOCIRCUITO
//ID102 - PROTEZIONE SOVRATENSIONE BATTERIA
//ID103 - PROTEZIONE SOTTOTENSIONE BATTERIA
//ID104 - PROTEZIONE SOVRATEMPERATURA BATTERIA DURANTE LA SCARICA
//ID105 - PROTEZIONE SOVRATEMPERATURA BATTERIA DURANTE LA CARICA
//ID106 - PROTEZIONE BASSA TEMPERATURA BATTERIA DURANTE LA SCARICA
//ID107 - PROTEZIONE BASSA TEMPERATURA BATTERIA DURANTE LA CARICA


//STATO SEMAFORO ROSSO ERRORI INVERTER 3PH HYD5000-HYD20000 ZSS

//ID01 - LA TENSIONE DI RETE E' TROPPO ALTA
//ID02 - LA TENSIONE DI RETE E' TROPPO BASSA
//ID03 - LA FREQUENZA DI RETE E' TROPPO ALTA
//ID04 - LA FREQUENZA DI RETE E' TROPPO BASSA
//ID05 - PERDITA DI CARICA
//ID06 - ERRORE FUNZIONE OVRT
//ID07 - ERRORE FUNZIONE LVRT
//ID08 - ERRORE NELL'ISOLAMENTO
//ID09 - SOVRATENSIONE TRANSITORIA DELLA RETE 1
//ID10 - SOVRATENSIONE TRANSITORIA DELLA RETE 2
//ID11 - ERRORE DI RETE
//ID12 - SOVRATENSIONE INVERTER
//ID17 - ERRORE NELLA MISURA DELLA CORRENTE DI RETE
//ID18 - ERRORE NELLA MISURA DELLA COMPONENTE DC DELLA CORRENTE DI RETE
//ID19 - ERRORE NELLA MISURA DELLA TENSIONE DI RETE (DC)
//ID20 - ERRORE NELLA MISURA DELLA TENSIONE DI RETE (AC)
//ID21 - ERRORE NELLA MISURA DELLA DISPERSIONE DI RETE (DC)
//ID22 - RRORE NELLA MISURA DELLA DISPERSIONE DI RETE (AC)
//ID23 - ERRORE NELLA MISURA DELLA COMPONENTE DCI DELLA TENSIONE DEL CARICO
//ID24 - ERRORE NELLA MISURA DELLA CORRENTE IN INGRESSO
//ID29 - ERRORE DI LETTURA DELLA CORRENTE DI DISPERSIONE
//ID30 - ERRORE DI LETTURA DELLA TENSIONE DI RETE
//ID33 - ERRORE COMUNICAZIONE SPI (DC)
//ID34 - ERRORE COMUNICAZIONE SPI (AC)
//ID35 - ERRORE CHIP (DC)
//ID36 - ERRORE CHIP (AC)
//ID37 - ERRORE POTENZA AUSILIARIA
//ID38 - ERRORE INTERNO
//ID41 - ERRORE NEL RILEVAMENTO DEL RELE'
//ID42 - BASSA IMPENDENZA ISOLAMENTO
//ID43 - ERRORE TERRA
//ID44 - ERRORE NELL'IMPOSTAZIONE MODALITA' INGRESSO
//ID45 - ERRORE CT
//ID47 - ERRORE IMPOSTAZIONI PARALLEO
//ID49 - PROTEZIONE TEMPERATURA BATTERIA
//ID50 - PROTEZIONE TEMPERATURA RADIATORE 1
//ID51 - PROTEZIONE TEMPERATURA RADIATORE 2
//ID52 - PROTEZIONE TEMPERATURA RADIATORE 3
//ID53 - PROTEZIONE TEMPERATURA RADIATORE 4
//ID54 - PROTEZIONE TEMPERATURA RADIATORE 5
//ID55 - PROTEZIONE TEMPERATURA RADIATORE 6
//ID57 - PROTEZIONE TEMPERATURA AMBIENTE 1
//ID58 - PROTEZIONE TEMPERATURA AMBIENTE 2
//ID59 - PROTEZIONE TEMPERATURA MODULO 1
//ID60 - PROTEZIONE TEMPERATURA MODULO 2
//ID61 - PROTEZIONE TEMPERATURA MODULO 3
//ID65 - TENSIONE RMS BUS NON BILANCIATA
//ID66 - VALORE DI TENSIONE TRANSITORIA DEL BUS NON BILANCIATA 
//ID67 - SOTTOTENSIONE DEL BUS DURANTE LA CONNESSIONE ALLA RETE
//ID68 - BASSA TENSIONE BUS
//ID69 - SOVRATENSIONE PV 
//ID70 - SOVRATENSIONE BATTERIA
//ID71 - PROTEZIONE SOVRATENSIONE LLC BUS
//ID72 - PROTEZIONE SOVRATENSIONE RMS SOFTWARE DEL BUS DC
//ID73 - PROTEZIONE SOVRATENSIONE ISTANTANEA SOFTWARE DEL BUS DC
//ID81 - PROTEZIONE SOVRATENSIONE ISTANTANEA SOFTWARE DEL BUS DC
//ID82 - PROTEZIONE SOVRACORRENTE DCI
//ID83 - PROTEZIONE CORRENTE ISTANTANEA IN USCITA
//ID84 - FLUSSO SOFTWARE BUCKBOOST
//ID85 - PROTEZIONE VALORE EFFETTIVO CORRENTE
//ID86 - PROTEZIONE SOVRACORRENTE PV SOFTWARE
//ID87 - FLUSSI PV IN PARALLELO NON BILANCIATO
//ID88 - CORRENTE IN USCITA NON BILANCIATA 
//ID97 - SOVRATENSIONE HARDWARE LLC BUS 
//ID98 - SOVRATENSIONE HARDWARE BUS
//ID99 - FLUSSI ECCESSIVI HARDWARE BUCKBOOST
//ID100 - FLUSSI ECCESSIVI HARDWARE BATTERIA
//ID102 - FLUSSI ECCESSIVI HARDWARE PV
//ID103 - FLUSSI ECCESSIVI HARDWARE AC IN USCITA
//ID110 - PROTEZIONE SOVRACCARICO 1
//ID111 - PROTEZIONE SOVRACCARICO 2
//ID112 - PROTEZIONE SOVRACCARICO 3
//ID113 - TEMPERATURA INTERNA TROPPO ALTA
//ID114 - FREQUENZA AC TROPPO ELEVATA
//ID115 - FREQUENZA AC TROPPO BASSA
//ID116 - TENSIONE AC TROPPO ALTA
//ID117 - TENSIONE AC TROPPO BASSA
//ID124 - PROTEZIONE TENSIONE BASSA DELLA BATTERIA
//ID125 - SPEGNIMENTO BATTERIA PER TENSIONE BASSA
//ID129 - ERRORE PERMANENTE HARDWARE PER SOVRACORRENTE IN USCITA
//ID130 - ERRORE SOVRATENSIONE BUS FISSA
//ID131 - ERRORE SOVRATENSIONE HARDWARE BUS
//ID132 - ERRORE OERMANENTE FLUSSO PV NON BILANCIATO
//ID133 - ERRORE PERMANENTE SOVRACORRENTE BATTERIA IN MODALITA' EPS
//ID134 - ERRORE SOVRACORRENTE TRANSITORIA BATTERIA IN USCITA
//ID135 - ERRORE PERMANENTE
//ID137 - ERRORE PERMANENTE IMPOSTAZIONI MODALITA' INGRESSO
//ID138 - ERRORE PERMANENTE SOVRACORRENTE INGRESSO
//ID139 - ERRORE PERMANENTE SOVRACORRENTE HARDWARE
//ID140 - ERRORE PERMANENTE RELE'
//ID141 - ERRORE PERMANENTE TENSIONE BUS NON BILANCIATA 
//ID145 - ERRORE USB
//ID146 - ERRORE WIFI
//ID147 - ERRORE BLUETOOTH
//ID148 - ERRORE ORLOGIO RTC
//ID149 - ERRORE SCHEDA DI COMUNICAZIONE EEPROM
//ID150 - ERRORE SCHEDA DI COMUNICAZIONE FLASH
//ID153 - SCI ERRORE COMUNICAZIONE (DC)
//ID154 - SCI ERRORE COMUNICAZIONE (AC)
//ID155 - SCI ERRORE
//ID156 - VERSIONE SOFTWARE DISCORDANTE
//ID157 - ERRORE COMUNICAZIONE BATTERIA LITIO CANALE 1
//ID158 - ERRORE COMUNICAZIONE BATTERIA LITIO CANALE 2
//ID161 - SPEGNIMENTO FORZATO
//ID162 - SPEGNIMENTO REMOTO
//ID163 - SPEGNIMENTO DRMs0
//ID165 - DERATING DA REMOTO
//ID166 - DERATING INTERFACCIA LOGICA
//ID167 - DERATING ANTI-RIFLUSSO
//ID169 - ERRORE VENTOLA 1
//ID170 - ERRORE VENTOLA 2
//ID171 - ERRORE VENTOLA 3
//ID172 - ERRORE VENTOLA 4
//ID173 - ERRORE VENTOLA 5
//ID174 - ERRORE VENTOLA 6
//ID177 - ALLARME SOVRATENSIONE BMS
//ID178 - ALLARME SOTTOTENSIONE BMS
//ID179 - ALLARME ALTA TEMPERATURA BMS
//ID180 - ALLARME BASSA TEMPERATURA BMS 
//ID181 - AVVERTIMENTO DI SOVRACCARICO IN CARICA E SCARICA DEL BMS
//ID182 - ALLARME CORTO CIRCUITO BMS


//STATO SEMAFORO ROSSO ERRORI INVERTER 1PH 3000TLM-6000TLM-V2

//ID01 - LA TENSIONE DI RETE E' TROPPO ALTA
//ID02 - LA TENSIONE DI RETE E' TROPPO BASSA
//ID03 - LA FREQUENZA DI RETE E' TROPPO ALTA
//ID04 - LA FREQUENZA DI RETE E' TROPPO BASSA
//ID05 - LA TENSIONE DI INGRESSO E' TROPPO BASSA
//ID06 - ERRORE FUNZIONE LVRT
//ID07 - ERRORE FUNZIONE OVRT
//ID09 - LA TENSIONE DI INGRESSO E' TROPPO ALTA
//ID10 - LA CORRENTE DI INGRESSO NON E' BILANCIATA
//ID11 - MODALITA' DI INGRESSO NON CORRETTO
//ID12 - GUASTO DELL'INTERRUTORE AUTOMATICO DIFFERENZIALE
//ID14 - LA CORRENTE DI INGRESSO E' TROPPO ALTA E HA CAUSATO L'ATTIVAZIONE DELLA PROTEZIONE HARDWARE
//ID15 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO L'ATTIVAZIONE DELLA PROTEZIONE HARDWARE
//ID16 - LA CORRENTE DI RETE E' TROPPO ALTA
//ID17 - ERRORE DI CAMPIONATURA DELLA CORRENTE DI RETE
//ID18 - ERRORE DI CAMPIONATURA DCI
//ID19 - ERRORE DI CAMPIONATURA DELLA TENSIONE DI RETE
//ID20 - ERRORE DI CAMPIONATURA GFCI
//ID21 - GUASTO AL CHIP MASTER
//ID22 - ERRORE  DELLA TENSIONE AUSILIARE
//ID23 - ERRORE DI CAMPIONATURA DELLA TENSIONE DI BUS
//ID24 - LA CORRENTE DI USCITA NON E' BILANCIATA
//ID25 - LA TENSIONE DEL BUS E' TROPPO BASSA
//ID26 - LA TENSIONE DEL BUS E' TROPPO ALTA
//ID27 - LA TENSIONE DEL BUS NON E' BILANCIATA
//ID28 - LA DCI E' TROPPO ALTA
//ID29 - LA CORRENTE DI RETE E' TROPPO ALTA
//ID30 - LA CORRENTE DI INGRESSO E' TROPPO ALTA
//ID33 - RISERVATO (CONTATTARE PRODUTTORI)
//ID49 - IL VALORE DELLA CAMPIONATURA DELLA TENSIONE DI RETE TRA IL DSP MASTER E IL DSP SLAVE NON E UGUALE
//ID50 - IL VALORE DI CAMPIONATURA DELLA FREQUENZA DI RETE TRA IL DSP MASTER E IL DSP SLAVE NON E' UGUALE.
//ID51 - IL VALORE DI CAMPIONATURA DELLA CORRENTE DELL'INTERRUTORE AUTOMATICO.
//ID52 - IL VALORE DI CAMPIONATURA DELLA CORRENTE DELL'INTERRUTORE AUTOMATICO DIFFERENZIALE (GFCI) TRA IL DSP MASTER E IL DSP SLAVE NON E' UGUALE
//ID53 - ERRORE DI COMUNICAZIONE SPI TRA IL DSP MASTER E IL DSP SLAVE
//ID54 - ERRORE DI COMUNICAZIONE SCI TRA IL DSP MASTER E IL DSP SLAVE
//ID55 - RELE'GUASTO
//ID56 - LA RESISTENZA DI ISOLAMENTO E' TROPPO BASSA
//ID57 - LA TEMPERATURA DELL'INVERTER E' TROPPO ALTA
//ID58 - LA TEMPERATURA DEL BOOST E' TROPPO ALTA
//ID59 - LA TEMPERATURA AMBIENTE E' TROPPO ALTA
//ID65 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO UN GUASTO HARDWARE IRREVERSIBILE
//ID66 - LA TENSIONE DEL BUS E' TROPPO ALTA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID67 - LA CORRENTE DI RETE E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID68 - LA CORRENTE DI INGRESSO E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID69 - LA TENSIONE DEL BUS E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID70 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID71 - MODALITA' DI INGRESSO SCORRETTA
//ID74 - LA CORRENTE DI INGRESSO E' TROPPO ALTA ED HA CAUSATO UN GUASTO IRRIMEDIABILE
//ID75 - LA EEPROM E' IRRECUPERABILE
//ID76 - LA EEPROM E' IRRECUPERABILE
//ID77 - IL RELE' HA GENERATO UN GUASTO PERMANENTE
//ID81 - DERATING A CAUSA DI TEMPERATURA TROPPO ALTA
//ID82 - L'INVERTER E' STATO DEPOTENZIATO A CAUSA DELLA FREQUENZA DI RETE TROPPO ALTA
//ID83 - L'INVERTER E' STATO DEPOTENZIATO ATTRAVERSO IL CONTROLLO REMOTO
//ID84 - L'INVERTER E' STATO SPENTO ATTRAVERSO IL CONTROLLO REMOTO
//ID85 - L'INVERTER E' STATO DEPOTENZIATO A CAUSA DI CORRENTE DI RETE TROPPO BASSA
//ID89 - RISERVATO (CONTATTARE PRODUTTORI)
//ID93 - ATTIVAZIONE PROTEZIONE SOVRATENSIONI CAUSATE DA FULMINI
//ID94 - IL SOFTWARE DELLA SCHEDA DI CONTROLLO E DELLA SCHEDA DI COMUNICAZIONE NON CORRISPONDE
//ID95 - LA SCHEDA DI COMUNICAZIONE EEPROM E' GUASTA
//ID96 - IL CHIP DELL'OROLOGIO RTC E' GUASTO
//ID97 - IL PAESE SELEZIONATO NON E' VALIDO
//ID98 - LA SCHEDA SD E' GUASTA
//ID99-ID100 - RISERVATO (CONTATTARE PRODUTTORI)


//STATO SEMAFORO ROSSO ERRORI INVERTER 1PH 1PH 1100TL-3000TL-V1

//ID01 - LA TENSIONE DI RETE E' TROPPO ALTA
//ID02 - LA TENSIONE DI RETE E' TROPPO BASSA
//ID03 - LA FREQUENZA DI RETE E' TROPPO ALTA
//ID04 - LA FREQUENZA DI RETE E' TROPPO BASSA
//ID05 - LA TENSIONE DI INGRESSO E' TROPPO BASSA
//ID06 - ERRORE FUNZIONE LVRT
//ID07 - ERRORE FUNZIONE OVRT
//ID09 - LA TENSIONE DI INGRESSO E' TROPPO ALTA
//ID10 - LA CORRENTE DI INGRESSO NON E' BILANCIATA
//ID11 - MODALITA' DI INGRESSO NON CORRETTO
//ID12 - GUASTO DELL'INTERRUTORE AUTOMATICO DIFFERENZIALE
//ID14 - LA CORRENTE DI INGRESSO E' TROPPO ALTA E HA CAUSATO L'ATTIVAZIONE DELLA PROTEZIONE HARDWARE
//ID15 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO L'ATTIVAZIONE DELLA PROTEZIONE HARDWARE
//ID16 - LA CORRENTE DI RETE E' TROPPO ALTA
//ID17 - ERRORE DI CAMPIONATURA DELLA CORRENTE DI RETE
//ID18 - ERRORE DI CAMPIONATURA DCI
//ID19 - ERRORE DI CAMPIONATURA DELLA TENSIONE DI RETE
//ID20 - ERRORE DI CAMPIONATURA GFCI
//ID21 - GUASTO AL CHIP MASTER
//ID22 - ERRORE  DELLA TENSIONE AUSILIARE
//ID23 - ERRORE DI CAMPIONATURA DELLA TENSIONE DI BUS
//ID24 - LA CORRENTE DI USCITA NON E' BILANCIATA
//ID25 - LA TENSIONE DEL BUS E' TROPPO BASSA
//ID26 - LA TENSIONE DEL BUS E' TROPPO ALTA
//ID27 - LA TENSIONE DEL BUS NON E' BILANCIATA
//ID28 - LA DCI E' TROPPO ALTA
//ID29 - LA CORRENTE DI RETE E' TROPPO ALTA
//ID30 - LA CORRENTE DI INGRESSO E' TROPPO ALTA
//ID33 - RISERVATO (CONTATTARE PRODUTTORI)
//ID49 - IL VALORE DELLA CAMPIONATURA DELLA TENSIONE DI RETE TRA IL DSP MASTER E IL DSP SLAVE NON E UGUALE
//ID50 - IL VALORE DI CAMPIONATURA DELLA FREQUENZA DI RETE TRA IL DSP MASTER E IL DSP SLAVE NON E' UGUALE.
//ID51 - IL VALORE DI CAMPIONATURA DELLA CORRENTE DELL'INTERRUTORE AUTOMATICO.
//ID52 - IL VALORE DI CAMPIONATURA DELLA CORRENTE DELL'INTERRUTORE AUTOMATICO DIFFERENZIALE (GFCI) TRA IL DSP MASTER E IL DSP SLAVE NON E' UGUALE
//ID53 - ERRORE DI COMUNICAZIONE SPI TRA IL DSP MASTER E IL DSP SLAVE
//ID54 - ERRORE DI COMUNICAZIONE SCI TRA IL DSP MASTER E IL DSP SLAVE
//ID55 - RELE'GUASTO
//ID56 - LA RESISTENZA DI ISOLAMENTO E' TROPPO BASSA
//ID57 - LA TEMPERATURA DELL'INVERTER E' TROPPO ALTA
//ID58 - LA TEMPERATURA DEL BOOST E' TROPPO ALTA
//ID59 - LA TEMPERATURA AMBIENTE E' TROPPO ALTA
//ID65 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO UN GUASTO HARDWARE IRREVERSIBILE
//ID66 - LA TENSIONE DEL BUS E' TROPPO ALTA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID67 - LA CORRENTE DI RETE E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID68 - LA CORRENTE DI INGRESSO E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID69 - LA TENSIONE DEL BUS E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID70 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID71 - MODALITA' DI INGRESSO SCORRETTA
//ID74 - LA CORRENTE DI INGRESSO E' TROPPO ALTA ED HA CAUSATO UN GUASTO IRRIMEDIABILE
//ID75 - LA EEPROM E' IRRECUPERABILE
//ID76 - LA EEPROM E' IRRECUPERABILE
//ID77 - IL RELE' HA GENERATO UN GUASTO PERMANENTE
//ID81 - DERATING A CAUSA DI TEMPERATURA TROPPO ALTA
//ID82 - L'INVERTER E' STATO DEPOTENZIATO A CAUSA DELLA FREQUENZA DI RETE TROPPO ALTA
//ID83 - L'INVERTER E' STATO DEPOTENZIATO ATTRAVERSO IL CONTROLLO REMOTO
//ID84 - L'INVERTER E' STATO SPENTO ATTRAVERSO IL CONTROLLO REMOTO
//ID85 - L'INVERTER E' STATO DEPOTENZIATO A CAUSA DI CORRENTE DI RETE TROPPO BASSA
//ID89 - RISERVATO (CONTATTARE PRODUTTORI)
//ID93 - ATTIVAZIONE PROTEZIONE SOVRATENSIONI CAUSATE DA FULMINI
//ID94 - IL SOFTWARE DELLA SCHEDA DI CONTROLLO E DELLA SCHEDA DI COMUNICAZIONE NON CORRISPONDE
//ID95 - LA SCHEDA DI COMUNICAZIONE EEPROM E' GUASTA
//ID96 - IL CHIP DELL'OROLOGIO RTC E' GUASTO
//ID97 - IL PAESE SELEZIONATO NON E' VALIDO
//ID98 - LA SCHEDA SD E' GUASTA
//ID99-ID100 - RISERVATO (CONTATTARE PRODUTTORI)


//STATO SEMAFORO ROSSO ERRORI INVERTER 1PH 3000TLM-6000TLM-V1

//ID01 - LA TENSIONE DI RETE E' TROPPO ALTA
//ID02 - LA TENSIONE DI RETE E' TROPPO BASSA
//ID03 - LA FREQUENZA DI RETE E' TROPPO ALTA
//ID04 - LA FREQUENZA DI RETE E' TROPPO BASSA
//ID05 - LA TENSIONE DI INGRESSO E' TROPPO BASSA
//ID06 - ERRORE FUNZIONE LVRT
//ID07 - ERRORE FUNZIONE OVRT
//ID09 - LA TENSIONE DI INGRESSO E' TROPPO ALTA
//ID10 - LA CORRENTE DI INGRESSO NON E' BILANCIATA
//ID11 - MODALITA' DI INGRESSO NON CORRETTO
//ID12 - GUASTO DELL'INTERRUTORE AUTOMATICO DIFFERENZIALE
//ID14 - LA CORRENTE DI INGRESSO E' TROPPO ALTA E HA CAUSATO L'ATTIVAZIONE DELLA PROTEZIONE HARDWARE
//ID15 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO L'ATTIVAZIONE DELLA PROTEZIONE HARDWARE
//ID16 - LA CORRENTE DI RETE E' TROPPO ALTA
//ID17 - ERRORE DI CAMPIONATURA DELLA CORRENTE DI RETE
//ID18 - ERRORE DI CAMPIONATURA DCI
//ID19 - ERRORE DI CAMPIONATURA DELLA TENSIONE DI RETE
//ID20 - ERRORE DI CAMPIONATURA GFCI
//ID21 - GUASTO AL CHIP MASTER
//ID22 - ERRORE  DELLA TENSIONE AUSILIARE
//ID23 - ERRORE DI CAMPIONATURA DELLA TENSIONE DI BUS
//ID24 - LA CORRENTE DI USCITA NON E' BILANCIATA
//ID25 - LA TENSIONE DEL BUS E' TROPPO BASSA
//ID26 - LA TENSIONE DEL BUS E' TROPPO ALTA
//ID27 - LA TENSIONE DEL BUS NON E' BILANCIATA
//ID28 - LA DCI E' TROPPO ALTA
//ID29 - LA CORRENTE DI RETE E' TROPPO ALTA
//ID30 - LA CORRENTE DI INGRESSO E' TROPPO ALTA
//ID33 - RISERVATO (CONTATTARE PRODUTTORI)
//ID49 - IL VALORE DELLA CAMPIONATURA DELLA TENSIONE DI RETE TRA IL DSP MASTER E IL DSP SLAVE NON E UGUALE
//ID50 - IL VALORE DI CAMPIONATURA DELLA FREQUENZA DI RETE TRA IL DSP MASTER E IL DSP SLAVE NON E' UGUALE.
//ID51 - IL VALORE DI CAMPIONATURA DELLA CORRENTE DELL'INTERRUTORE AUTOMATICO.
//ID52 - IL VALORE DI CAMPIONATURA DELLA CORRENTE DELL'INTERRUTORE AUTOMATICO DIFFERENZIALE (GFCI) TRA IL DSP MASTER E IL DSP SLAVE NON E' UGUALE
//ID53 - ERRORE DI COMUNICAZIONE SPI TRA IL DSP MASTER E IL DSP SLAVE
//ID54 - ERRORE DI COMUNICAZIONE SCI TRA IL DSP MASTER E IL DSP SLAVE
//ID55 - RELE'GUASTO
//ID56 - LA RESISTENZA DI ISOLAMENTO E' TROPPO BASSA
//ID57 - LA TEMPERATURA DELL'INVERTER E' TROPPO ALTA
//ID58 - LA TEMPERATURA DEL BOOST E' TROPPO ALTA
//ID59 - LA TEMPERATURA AMBIENTE E' TROPPO ALTA
//ID65 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO UN GUASTO HARDWARE IRREVERSIBILE
//ID66 - LA TENSIONE DEL BUS E' TROPPO ALTA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID67 - LA CORRENTE DI RETE E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID68 - LA CORRENTE DI INGRESSO E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID69 - LA TENSIONE DEL BUS E' SBILANCIATA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID70 - LA CORRENTE DI RETE E' TROPPO ALTA E HA CAUSATO UN GUASTO IRREVERSIBILE
//ID71 - MODALITA' DI INGRESSO SCORRETTA
//ID74 - LA CORRENTE DI INGRESSO E' TROPPO ALTA ED HA CAUSATO UN GUASTO IRRIMEDIABILE
//ID75 - LA EEPROM E' IRRECUPERABILE
//ID76 - LA EEPROM E' IRRECUPERABILE
//ID77 - IL RELE' HA GENERATO UN GUASTO PERMANENTE
//ID81 - DERATING A CAUSA DI TEMPERATURA TROPPO ALTA
//ID82 - L'INVERTER E' STATO DEPOTENZIATO A CAUSA DELLA FREQUENZA DI RETE TROPPO ALTA
//ID83 - L'INVERTER E' STATO DEPOTENZIATO ATTRAVERSO IL CONTROLLO REMOTO
//ID84 - L'INVERTER E' STATO SPENTO ATTRAVERSO IL CONTROLLO REMOTO
//ID85 - L'INVERTER E' STATO DEPOTENZIATO A CAUSA DI CORRENTE DI RETE TROPPO BASSA
//ID89 - RISERVATO (CONTATTARE PRODUTTORI)
//ID93 - ATTIVAZIONE PROTEZIONE SOVRATENSIONI CAUSATE DA FULMINI
//ID94 - IL SOFTWARE DELLA SCHEDA DI CONTROLLO E DELLA SCHEDA DI COMUNICAZIONE NON CORRISPONDE
//ID95 - LA SCHEDA DI COMUNICAZIONE EEPROM E' GUASTA
//ID96 - IL CHIP DELL'OROLOGIO RTC E' GUASTO
//ID97 - IL PAESE SELEZIONATO NON E' VALIDO
//ID98 - LA SCHEDA SD E' GUASTA
//ID99-ID100 - RISERVATO (CONTATTARE PRODUTTORI)


//STATO SEMAFORO ROSSO ERRORI INVERTER 3000SP - RETROFIT

//ID01 - LA TENSIONE DI RETE E' TROPPO ALTA
//ID02 - LA TENSIONE DI RETE E' TROPPO BASSA
//ID03 - LA FREQUENZA DI RETE E' TROPPO ALTA
//ID04 - LA FREQUENZA DI RETE E' TROPPO BASSA
//ID05 - LA TENSIONE DI INGRESSO E' TROPPO BASSA
//ID06 - ERRORE FUNZIONE LVRT
//ID07 - ERRORE FUNZIONE OVRT
//ID08 - TENSIONE PV TROPPO ALTA
//ID09 - TENSIONE SULLA LINEA LLC TROPPO ALTA. INTERVENTO DI PROTEZIONE HARDWARE
//ID10 - TENSIONE DI BOOST TROPPO ALTA. INTERVENTO DI PROTEZIONE HARDWARE
//ID11 - CORRENTE DI BUCKBOOST TROPPO ALTA. INTERVENTO DI PROTEZIONE
//ID12 - BATTERIA TROPPO ALTA. INTERVENTO PROTEZIONE HARDWARE
//ID15 - CORRENTE IN RETE TROPPO ALTA. INTERVENTO DI PROTEZIONE HARDWARE
//ID17 - ERRORE DI CAMPIONAMENTO DELLA CORRENTE DI RETE
//ID18 - ERRORE DI CAMPIONAMNETO DCI 
//ID19 - ERRORE DI CAMPIONAMENTO DELLA TENSIONE DI RETE
//ID20 - ERRORE DI CAMPIONATURA GFCI
//ID21 - FAULT DEL MICROPROCESSORE 
//ID22 - ERRORE SULLA TENSIONE DI ALIMENTAZIONE AUSILIARIA 
//ID25 - TENSIONE SULLA LINEA LLC TROPPO ALTA
//ID26 - TENSIONE SULLA LINEA DI COMUNICAZIONE TROPPO ALTA. INTERVENTO DI PROTEZIONE SOFTWARE
//ID27 - CORRENTE DI BATTERIA TROPPO ALTA
//ID28 - CORRENTE SUL DCI TROPPO ALTA
//ID29 - CORRENTE DI RETE TROPPO ALTA
//ID30 - CORRENTE SUL BUCK TROPPO ALTA
//ID31 - CORRENTE DI USCITA TROPPO ALTA
//ID34 - SOVRACCARICO
//ID35 - IL CT E' GUASTO
//ID49 - MISURE DI TENSIONE DI RETE TRA DSP PRINCIPALE E DSP SECONDARIO NON ALLINEATE
//ID50 - MISURE DI FREQUENZA DI RETE TRA DSP PRINCIPALE E DSP SECONDARIO NON ALLINEATE
//ID51 - MISURE DCI TRA DSP PRINCIPALE E DSP SECONDARIO NON ALLINEATE
//ID52 - ERRORE DI COMUNICAZIONE CON LA BATTERIA
//ID53 - ERRORE COMUNICAZIONE SPI
//ID54 - ERRORE COMUNICAZIONE SCI
//ID55 - ERRORE RELAYS
//ID56 - LA RESISTENZA DI ISOLAMENTO E' TROPPO BASSA
//ID57 - TEMPERATURA DI BATTERIA TROPPO ALTA
//ID58 - TEMPERATURA DEL DISSIPATORE INVERTER TROPPO ALTA
//ID59 - TEMPERATURA AMBIENTE TROPPO ALTA
//ID65 - CORRENTE DI RETE TROPPO ALTA. FAULT HARDWARE NON RECUPERABILE
//ID66 - TENSIONE SUL BUS TROPPO ALTA. FAULT HARDWARE NON RECUPERABILE
//ID67 - FAULT NON RECUPERABILE SULLA BATTERIA IN MODALITA' EPS
//ID70 - CORRENTE DI RETE TROPPO ALTA. FAULT HARDWARE NON RECUPERABILE
//ID75 - EEPROM ILLEGIBILE
//ID76 - EEPROM ILLEGIBILE
//ID77 - FAULT PERMANENTE SUL RELAYS 
//ID81 - LA TEMPERATURA INTERNA E' TROPPO ALTA
//ID82 - LA FREQUENZA AC E' TROPPO ALTA
//ID83 - SEGNALE REMOTO DI LIMITAZIONE CARICO
//ID84 - SEGNALE DI SPEGNIMENTO DELL'INVERTER 3000SP
//ID85 - TENSIONE BATTERIA BASSA
//ID86 - TENSIONE BATTERIA BASSA
//ID94 - LA VERSIONE FIRMWARE INSTALLATA NON E'ADEGUATA AL TIPO DI INVERTER
//ID95 - EEPROMb DELLA SCHEDA DI COMUNICAZIONE ILLEGIBILE
//ID96 - ERRORE OROLOGIO
//ID97 - NAZIONE SELEZIONATA NON VALIDA
//ID98 - ERRORE SD CARD
//ID99 - IL WIFI E' IN ERRORE
//ID100 - PROTEZIONE DI SOVRACORRENTE DI SCARICA BATTERIA
//ID101 - PROTEZIONE DA CORTO CIRCUITO DI SCARICA BATTERIA
//ID102 - PROTEZIONE SOVRATENSIONE DI BATTERIA
//ID103 - PROTEZIONE SOTTOTENSIONE DI BATTERIA
//ID104 - PROTEZIONE DI SOVRATEMPERATURA DI SCARICA BATTERIA
//ID105 - PROTEZIONE SOVRATEMPERATURA DI CARICA BATTERIA
//ID106 - PROTEZIONE SOTTOTEMPERATURA DI SCARICA BATTERIA
//ID107 - PROTEZIONE DI SOTTOTEMPERATURA DI CARICA BATTERIA


//STATO SEMAFORO ROSSO ERRORI INVERTER 1PH BZT5000

//ID01 - LA TENSIONE DI ALIMENTAZIONE DI RETE E' TROPPO ELEVATA
//ID02 - LA TENSIONE DELLA RETE ELETTRICA E' TROPPO BASSA
//ID03 - LA FREQUENZA DELLA RETE ELETTRICA E' TROPPO ELEVATA
//ID04 - LA FREQUENZA DELLA RETE ELETTRICA E' TROPPO BASSA
//ID06 - OVRT
//ID07 - LVRT
//ID08 - ERRORE PROTEZIONE ISLAND
//ID09 - SOVRATENSIONE TRANSITORIA 1 DELLA TENSIONE DI RETE
//ID10 - SOVRATENSIONE TRANSITORIA 2 DELLA TENSIONE DI RETE
//ID12 - SOVRATENSIONE O SOTTOTENSIONE DELL'INVERTER 
//ID13 - INVERSIONE DI CORRENTE PCC E IL TEMPO SUPERA I REQUISITI DI SICUREZZA
//ID17 - ERRORE DI CAMPIONAMENTO DELLA CORRENTE DI RETE
//ID18 - ERRORE DEL CAMPIONAMENTO DCI
//ID20 - ERRORE DI CAMPIONAMENTO DELLA TENSIONE DI RETE
//ID23 - ERRORE DI CAMPIONAMENTO DCV
//ID32 - RELE' N-PE RILEVATO COME CIRCUITO APERTO
//ID33 - ERRORE DI COMUNICAZIONE SPI (DC)
//ID34 - ERRORE DI COMUNICAZIONE SPI (AC)
//ID37 - ERRORE POTENZA AUSILIARIA
//ID38 - L'INVERTER NON GENERA NULLA
//ID47 - NON E' PRESENTE UNA MASTER O E' DUPLICATA
//ID56 - ENV NTC FAULT
//ID57 - LA TEMPERATURA AMBIENTALE E' TROPPO ELEVATA
//ID58 - TEMPERATURA DEL DISSIPATORE INVERTER TROPPO ALTA
//ID59 - LA TEMPERATURA DEL COMPONENTE INTERNO A E' TROPPO ELEVATA
//ID60 - LA TEMPERATURA DEL COMPONENTE INTERNO B E' TROPPO ELEVATA
//ID67 - LA TENSIONE DEL BUS CC INTERNA E' TROPPO BASSA
//ID71 - LA TENSIONE DEL BUS CC INTERNA E' TROPPO BASSA
//ID72 - IL VALORE RMS DELLA TENSIONE DEL BUS E' TROPPO ELEVATO E HA FATTO SCATTARE LA PROTEZIONE DEL SOFTWARE
//ID73 - IL VALORE ISTANTANEO DELLA TENSIONE DEL BUS E' TROPPO ELEVATO E HA FATTO SCATTARE LA PROTEZIONE DEL SOFTWARE
//ID82 - IL COMPONENTE CC DELLA CORRENTE DI RETE E' TROPPO ELEVATO
//ID83 - PROTEZIONE DA SOVRACORRENTE IN USCITA ISTANTANEA
//ID92 - PROTEZIONE SOVRACORRENTE IN USCITA SUL LUNGO TERMINE
//ID94 - LA CORRENTE DI CARICA/SCARICA PRIMARIA E' TROPPO ELEVATA E HA FATTO SCATTARE LA PROTEZIONE DELL'HARDWARE
//ID95 - LA CORRRENTE DEL BUS E' TROPPO ELEVATA E HA FATTO SCATTARE LA PROTEZIONE SOFTWARE
//ID100 - LA CORRENTE DELLA BATTERIA E' TROPPO ELEVATA E HA FATTO SCATTARE LA PROTEZIONE DELL'HARDWARE
//ID101 - IL TUBO GAN PRIMARIO NON FUNZIONA
//ID103 - LA CORRENTE DELLA RETE PRINCIPALE E' TROPPO ELEVATA E HA FATTO SCATTARE LA PROTEZIONE HARDWARE
//ID105 - ERRORE DI COMUNICAZIONE CON L'UNITA' CONTATORE
//ID106 - IL NUMERO DI SERIE E' ERRATO
//ID107 - LA VERSIONE HARDWARE NON CORRISPONDE
//ID108 - NON VIENE RAGGIUNTA LA TENSIONE CA DOPO L'AVVIO DEL GENERATORE
//ID109 - IL GENERATORE E' SOVRACCARICO
//ID110 -  LEGGERO SOVRACCARICO
//ID111 - SOVRACCARICO MODERATO 
//ID112 - SOVRACCARICO GRAVE 
//ID140 - ERRORE PERMANENTE DEL RELE' DELLA RETE PRINCIPALE 
//ID149 - L'EEPROM DELLA SCHEDA DI COMUNICAZIONE E' GUASTO
//ID150 - IL FLASH DELLA SCHEDA DI COMUNICAZXIONE E' GUASTO
//ID152 - LA VERSIONE DELLA NORMATIVA SULLA SICUREZZA E' SCORRETTA
//ID153 - ERRORE DI COMUNICAZIONE SCI (DC)
//ID154 - ERRORE DI COMUNICAZIONE SCI (AC)
//ID176 - L'INTERRUTORE DI CONTROLLO DEL RISCALDATORE DELLA BATTERIA NON FUNZIONA
//ID177 - LA TENSIONE DELLA BATTERIA E' TROPPPO ELEVATA 
//ID178 - LA TENSIONE DELLA BATTERIA E' TROPPO BASSA
//ID181 - PROTEZIONE SOVRACORRENTE DELLA BATTERIA 
//ID182 - PROTEZIONE DEL CORTOCIRCUITO BMS
//ID186 - LA TEMPERATURA DELLA BATTERIA E' TROPPO ELEVATA DURANTE LA SCARICA
//ID187 - LA TEMPERATURA DELLA BATTERIA E' TROPPO BASSA DUREANTE LA SCARICA
//ID188 - LA TEMPERATURA DELLA BATTERIA E' TROPPO ELEVATA DURANTE LA CARICA
//ID190 - LA TEMPERATURA DELLA BATTERIA E' TROPPO BASSA DURANTE LA CARICA
//ID274 - LA VERSIONE DEL PROTOCOLLO DI COMUNICAZIONE TRA ARM E DSP NON E' COERENTE
//ID455 - ERRORE DEL CAMPIONAMENTO DELLA TENSIONE DELL'INVERTER
//ID456 - CAMPIONAMENTO DELLA TENSIONE DELL'INVERTER E DELLA TENSIONE EPS NON VALIDO
//ID457 - ERRORE DI CAMPIONAMENTO DELLA TENSIONE DEL BUS INTERNO
//ID458 - ERRORE DI CAMPIONAMENTO DELLA CORRENTE DEL BUS INTERNO
//ID460 - LA CORRENTE PRIMARIA E' TROPPPO ELEVATA E HA FATTO SCATTARE LA PROTEZIONE DELL'HARDWARE
//ID473 - C'E' UN PROBLEMA CON IL CONTEROLLO DELLA POTENZA PER LA SCARICA DELLA BATTERIA
//ID474 - C'E' UN PROBLEMA CON IL CONTROLLO DELLA POTENZA PER LA CARICA DELLA BATTERIA
//ID475 - ERRORE DI CAMPIONAMENTO DELLA TEMPERATURA DELLA CELLA BATTERIA
//ID476 - DIFFERENZA DI TENSIONE ECCESSIVA TRA LE CELLE 
//ID477 - DIFFERENZA DI TENSIONE ECCESSIVA TRA LA TENSIONE COMPLESSIVA E LA SOMMA DELLE TENSIONI DELLE CELLE


//STATO SEMAFORO ROSSO ERRORI INVERTER 1PH HYD3000-HYD6000 ZSS HP

//ID001 - LA TENSIONEDI RETE E' ECCESSIVA
//ID002 - LA TENSIONE DI RETE E' INSUFFICIENTE
//ID003 - LA FREQUENZA DI RETE E' ECCESSIVA
//ID004 - LA FREQUENZA DI RETE E' INSUFFICIENTE
//ID005 - ANOMALIA DISPERSIONE DI CARICA
//ID006 - LA FUNZIONALITA' OVRT E' DIFETTOSA
//ID007 - LA FUNZIONALITA' LVRT E' DIFETTOSA
//ID008 - ERRORE PROTEZIONE ISOLAMENTO
//ID009 - SOVRATENSIONE TRANSITORIA DELLA TENSIONE DI RETE 1
//ID010 - SOVRATENSIONE TRANSITORIA DELLA TENSIONE DI RETE 2
//ID011 - ERRORE TENSIONE DELLA LINEA DELLA RETE DI ALIMENTAZIONE
//ID012 - SOVRATENSIONE INVERTER 
//ID017 - ERRORE DI CAMPIONAMENTO DELLA CORRENTE DELLA RETE DI ALIMENTAZIONE
//ID018 - ERRORE DI CAMPIONAMENTO DELLA COMPONENTE CC DELLA RETE ELETTRICA
//ID019 - ERRORE DI CAMPIONAMENTO DELLA TENSIONE DELLA RETE ELETTRICA (CC)
//ID020 - ERRORE DI CAMPIONAMENTO DELLA TENSIONE DELLA RETE ELETTRICA (CA)
//ID021 - ERRORE DI CAMPIONAMENTO CORRENTE DI DISPERSIONE (CC)
//ID022 - ERRORE DI CAMPIONAMENTO CORRENTE DI DISPERSIONE (CA)
//ID023 - ERRORE NEL CAMPIONAMENTO DEI COMPONENTI IN CC DELLA TENSIONE DI CARICO 
//ID024 - ERRORE NEL CAMPIONAMENTO DELLA CORRENTE DI INGRESSO CC
//ID029 - ERRORE DI COERENZA DELLA CORRENTE DI DISPERSIONE
//ID030 - ERRORE DI COERENZADELLA TENSIONE DI RETE
//ID033 - ERRORE DI COMUNICAZIONE SPI (CC)
//ID034 - ERRORE DI COMUNICAZIONE SPI (CA)
//ID035 - ERRORE CHIP (CC)
//ID036 - ERRORE CHIP (CA)
//ID037 - ERRORE ALIMENTAZIONE AUSILIARIA
//ID041 - ANOMALIA RILEVAMENTO RELE'
//ID042 - BASSA IMPEDENZA DI ISOLAMENTO
//ID043 - MASSA DIFETTOSA
//ID044 - ERRORE DURANTE L'IMPOSTAZIONE DELLA MODALITA' DI INGRESSO
//ID045 - ERRORE CT
//ID047 - ERRORE PARALELLO
//ID048 - ERRORE VENTOLA
//ID049 - PROTEZIONE DALLA TEMPERATURA DELLA BATTERIA
//ID050 - PROTEZIONE DALLA TEMPERATURA DEL RADIATORE 1
//ID051 - PROTEZIONE DALLA TEMPERATURA DEL RADIATORE 2
///ID052 - PROTEZIONE DALLA TEMPERATURA DEL RADIATORE 3
//ID053 - PROTEZIONE DALLA TEMPERATURA DEL RADIATORE 4
//ID054 - PROTEZIONE DALLA TEMPERATURA DEL RADIATORE 5
//ID055 - PROTEZIONE DALLA TEMPERATURA DEL RADIATORE 6
//ID057 - PROTEZIONE DALLA TEMPERATURA AMBIENTE 1
//ID058 - PROTEZIONE DALLA TEMPERATURA AMBIENTE 2
//ID059 - PROTEZIONE DALLA TEMPERATURA DEL MODULO 1
//ID060 - PROTEZIONE DALLA TEMPERATURA DEL MODULO 2
//ID061 - PROTEZIONE DALLA TEMPERATURA DEL MODULO 3
//ID065 - TENSIONE BUS RMS NON BILANCIATA
//ID066 - IL VALORE TRANSITORIO DELLA TENSIONE DEL BUS E' SBILANCIATO 
//ID067 - SOTTOTENSIONE DEL BUS DURANTE IL COLLEGAMENTO ALLA RETE 
//ID068 - TENSIONE DEL BUS BASSA
//ID069 - SOVRATENSIONE FV
//ID070 - SOVRATENSIONE DELLA BATTERIA
//ID071 - PROTEZIONE DA SOVRATENSIONE BUS LLC 
//ID072 - SOVRATENSIONE SOFTWARE RMS BUS DELL'INVERTER
//ID073 - SOVRATENSIONE SOFTWARE VALORE ISTANTANEO TENSIONE BUS DELL'INVERTER
//ID081 - PROTEZIONE SOFTWARE SOVRACORRENTE BATTERIA
//ID082 - PROTEZIONE DA SOVRACORRENTE DCI
//ID083 - PROTEZIONE CORRENTE USCITA ISTANTANEA
//ID084 - FLUSSO SOFTWARE BUCKBOOST
//ID085 - PROTEZIONE CORRENTE VALORE EFFETTIVO IN USCITA
//ID086 - PROTEZIONE SOFTWARE SOVRACORRENTE FV
//ID087 - FLUSSI FV IN PARALLELO NON OMOGENEI 
//ID088 - CORRENTE IN USCITA NON BILANCIATA 
//ID097 - SOVRATENSIONE HARDWARE BUS LLC
//ID098 - SOVRATENSIONE HARDWARE BUS INVERTER 
//ID099 - FLUSSI ECCESSIVI HARDWARE BUCKBOOST
//ID100 - FLUSSI ECCESSIVI HARDWARE BATTERIA
//ID102 - FLUSSI ECCESSIVI HARDWARE FV
//ID103 - FLUSSI ECCESSIVI HARDWARE USCITA AC
//ID105 - METER NON TROVATO
//ID110 - PROTEZIONE SOVRACCARICO 1
//ID111 - PROTEZIONE SOVRACCARICO 2
//ID112 - PROTEZIONE SOVRACCARICO 3
//ID113 - TEMPERATURA INTERNA ECCESSIVA 
//ID114 - FREQUENZA CA ECCESSIVA
//ID115 - FREQUENZA CA INSUFFICIENTE
//ID116 - TENSIONE CA ECCESSIVA
//ID117 - TENSIONE CA INSUFFICIENTE
//ID124 - PROTEZIONE BASSA TENSIONE DELLA BATTERIA 
//ID125 - ARRESTO PER BASSA TENSIONE DELLA BATTERIA
//ID129 - ERRORE PERMANENTE SOVRACORRENTE HARDWARE IN USCITA
//ID130 - ERRORE SOVRATENSIONE BSU PERMANENTE
//ID131 - ERRORE SOVRATENSIONE HARDWARE BUS PERMANENTE
//ID132 - ERRORE PERMANENTE FLUSSO IRREGOLARE FV
//ID133 - ERRORE PERMANENTE DA SOVRACORRENTE DELLA BATTERIA IN MODALITA' EPS
//ID134 - ERRORE PERMANENTE SOVRACORRENTE TRANSITORIA IN USCITA 
//ID135 - ERRORE PERMANENTE CORRENTE IN USCITA NON BILANCIATA 
//ID137 - ERRORE PERMANENTE DI IMPOSTAZIONE DELLA MODALITA' DI INGRESSO
//ID138 - ERRORE PERMANENTE DA SOVRACORRENTE IN INGRESSO
//ID139 - ERRORE PERMANENTE SOVRACORRENTE HARDWARE IN INGRESSO
//ID140 - ERRORE RELE' PERMANENTE 
//ID141 - GUASTO PERMANENTE TENSIONE DEL BUS NON BILANCIATA
//ID145 - GUASTO USB
//ID146 - ERRORE WI-FI 
//ID147 - ERRORE BLEUTOOTH
//ID148 - GUASTO DELL'OROLOGIO RTC
//ID149 - ERRORE EEPROM SCHEDA DI COMUNICAZIONE
//ID150 - ERRORE FLASH SCHEDA DI COMUNICAZIONE
//ID152 - ERRORE VERSIONE SAFETY NON COERENTE CO LA VERSIONE FIRMWARE DELL'INVERTER
//ID153 - ERRORE DI COMUNICARE SCI (CC)
//ID154 - ERRORE DI COMUNICAZIONE SCI (CA)
//ID155 - ERRORE DI COMUNICAZIONE SCI (FUSIBILE)
//ID156 - VERSIONI SOFTWARE INCOERENTI
//ID157 - ERRORE DI COMUNICAZIONE DELLA BATTERIA AL LITIO
//ID161 - SPEGNIMENTO FORZATO
//ID162 - SPEGNIMENTO REMOTO
//ID163 - ARRESTO DRMS0
//ID165 - DERATING REMOTO
//ID166 - DERATING INTERFACCIA LOGICA
//ID167 - DERATING ANTI-REFLUSSO
//ID169 - GUASTO VENTOLA
//ID175 - GUASTO VENTOLA
//ID177 - ALLARME SOVRATENSIONE BMS
//ID178 - ALLARME SOTTOTENSIONE BMS
//ID179 - AVVISO DI TEMPERATURA ELEVATA BMS 
//ID180 - ALLARME DI BASSA TEMPERATURA BMS 
//ID181 - AVVISO DI SOVRACCARICO IN CARICA E SCARICA DEL BMS
//ID182 - ALLARME CORTOCIRCUITO BMS


// STATO SEMAFORO ROSSO ERRORI INVERTER 1PH 3000TLM-6000TLM-V3
//ID01 - LA TENSIONE DI RETE E' ECCESSIVA
//ID02 - LA TENSIONE DI RETE E' INSUFFICIENTE
//ID03 - LA FREQUENZA DI RETE E' INSUFFICIENTE
//ID04 - LA FREQUENZA DI RETE E' INSUFFICIENTE
//ID05 - INTERRUTORE AUTOMATICO DIFFRENZIALE DIFETTOSO
//ID06 - OVRT DIFETTOSO
//ID07 - LVRT DIFETTOSO
//ID08 - ISOLAMENTO DIFETTOSO 
//ID09 - TENSIONE ISTANTANEA DI RETE ECCESSIVA 1
//ID10 - TENSIONE ISTANTANEA DI RETE ECCESSIVA 2
//ID11 - TENSIONE DI LINEA DIFETTOSA
//ID12 - SOVRATENSIONE INVERTER
//ID17 - ERRORE DEL CAMPIONAMENTO DELLA CORRENTE DI RETE
//ID18 - ERRORE DI CAMPIONAMENTO DCI
//ID19 - CAMPIONAMENTO TENSIONE DI RETE DIFETTOSO (LATO CC)
//ID20 - CAMPIONAMENTO TENSIONE DI RETE DIFETTOSO (LATO CA)
//ID21 - CAMPIONAMENTO DI DISPERSIONE DI CORRENTE (LATO CC)
//ID22 - CAMPIONAMENTO DI DISPERSIONE CORRENTE (LATO AC)
//ID23 - CAMPIONAMENTO DELLA DERIVAZIONE DI CORRENTE DIFETTOSO
//ID24 - CAMPIONAMENTO DELLA CORRENTE DI INGRESSO CC DIFETTOSO
//ID29 - IL VALORE DI CAMPIONAMENTO GFCI TRA IL DSP MASTER E IL DSP SLAVE NON E' COERENTE
//ID30 - IL VALORE DI CAMPIONAMENTO DELLA TENSIONE DI RETE TRA MASTER E SLAVE NON E' COERENTE
//ID31 - ERRORE CONSISTENZA 3 RIGHE DCI
//ID33 - COMUNICAZIONE SPI DIFETTOSA (LATO CC) 
//ID34 - COMUNICAZIONE SPI DIFETTOSA (LATO AC)
//ID35 - CHIP DIFETTOSO (LATO CC)
//ID36 - CHIP DIFETTOSO (LATO AC)
//ID37 - GUASTO ALIMENTAZIONE AUSILIARIA 
//ID41 - RELE' DIFETTOSO
//ID42 - ISOLAMENTO INFERIORE DIFETTOSO
//ID43 - MASSA DIFETTOSA
//ID44 - MODALITA' DI IMMISSIONE NON CORRETTA
//ID45 - ANOMALIA CT
//ID46 - ERRORE DI CONNESSIONE INGRESSO INVERTITO
//ID47 - RISERVATO (CONTATTARE PRODUTTORI)
//ID48 - IL NUMERO DI SERIE NON CORRISPONDE AL TIPO
//ID49 - RISERVATO (CONTATTARE PRODUTTORI)
//ID50 - PROTEZIONE DA SURRISCALDAMENTO DEL DISSIPATORE DI CALORE 1
//ID51 - RISERVATO (CONTATTARE PRODUTTORI)
//ID52 - RISERVATO (CONTATTARE PRODUTTORI)
//ID53 - RISERVATO (CONTATTARE PRODUTTORI)
//ID54 - RISERVATO (CONTATTARE PRODUTTORI)
//ID55 - RISERVATO (CONTATTARE PRODUTTORI)
//ID57 - PROTEZIONE TEMPERATURA AMBIENTE 1
//ID58 - RISERVATO (CONTATTARE PRODUTTORI)
//ID59 - PROTEZIONE SOVRATEMPERATURA MODELLO 1
//ID60 - RISERVATO (CONTATTARE PRODUTTORI)
//ID61 - RISERVATO (CONTATTARE PRODUTTORI)
//ID65 - VALORE RMS SBILANCIATO DELLA TENSIONE DEL BUS
//ID66 - VALORE ISTANTANEO SBILANCIATO DELL TENSIONE DEL BUS
//ID67 - SOTTOTENSIONE DEL BUS DURANTE IL COLLEGAMENTO ALLA RETE
//ID68 - TENSIONE DEL BUS BASSA
//ID69 - SOVRATENSIONE FV
//ID70 - RISERVATO (CONTATTARE PRODUTTORI)
//ID71 - SOVRATENSIONE LLCBUS
//ID72 - SOFTWARE DI SOVRATENSIONE DEL BUS DELL'INVERTER
//ID73 - SOFTWARE DI SOVRATENSIONE VALORE ISTANTANEO TENSIONE BUS INVERTER
//ID81 - RISERVATO (CONTATTARE PRODUTTORI)
//ID82 - SOVRACORRENTE DCI DIFFETTOSA
//ID83 - PROTEZIONE CORRENTE DI USCITA ISTANTANEA
//ID84 - SOVRACORRENTE SOFTWARE BUCKBOOST 
//ID85 - PROTEZIONE CORRENTE RMS DI USCITA
//ID86 - PROTEZIONE SOFTWARE SOVRACORRENTE FV
//ID87 - SQUILIBRIO FV PARALLELO
//ID88 - SQUILIBRIO CORRENTE DI USCITA
//ID89 - ERRORE ARCO
//ID97 - SOVRATENSIONE HARDWARE LLC
//ID98 - SOVRATENSIONE HARDWARE BUS INVERTER
//ID99 - SOVRACORRENTE HARDWARE BUCKBOOST
//ID100 - RISERVATO (CONTATTARE PRODUTTORI)
//ID102 - SOVRACORRENTE HARDWARE FV
//ID103 - SOVRACORRENTE HARDWARE USCITA CA
//ID110 - PROTEZIONE DA SOVRACCARICO 1
//ID111 - PROTEZIONE DA SOVRACCARICO 2
//ID112 - PROTEZIONE DA SOVRACCARICO 3
//ID113 - DETERING TEMPERATURA
//ID114 - DETERING FREQUENZA 
//ID115 - CARICO DI FREQUENZA 
//ID116 - DERATING DI TENSIONE 
//ID117 - CARICO DI TENSIONE
//ID124 - RISERVATO (CONTATTARE PRODUTTORI)
//ID125 - ERRORE PERMANENTE HARDWARE DI SOVRACORRENTE IN USCITA
//ID130 - ERRORE PERMANENTE  SOVRATENSIONE BUS
//ID131 - ERRORE PERMANENTE HARDWARE SOVRATENSIONE BUS 
//ID132 - ERRORE PERMANENTE CORRENTE SQUILIBRIO FV
//ID133 - RISERVATO (CONTATTARE PRODUTTORI)
//ID134 - ERRORE PERMANENTE SOVRACORRENTE TRANSITORIA DI USCITA
//ID135 - ERRORE PERMANENTE SCOMPENSO CORRENTE DI USCITA
//ID137 - ERRORE PERMANENTE DI CONFIGURAZIONE DELLA MODALITA' DI INGRESSO
//ID138 - ERRORE PERMANENTE DA SOVRACORRENTE IN INGRESSO
//ID139 - ERRORE PERMANENTE SOVRACORRENTE HARDWARE IN INGRESSO
//ID140 - ERRORE PERMANENTE DEL RELE' 
//ID141 - ERRORE PERMANENTE BUS SBILANCIATO 
//ID142 - ERRORE SPD CC
//ID143 - ERRORE SPD CA
//ID145 - ERRORE USB
//ID146 - ERRORE WI-FI 
//ID147 - ERRORE BLUETOOTH
//ID148 - ERRORE RTCCLOCK
//ID149 - ERRORE EEPROM SCHEDA DI COMUNICAZIONE 
//ID150 - ERRORE FLASH SCHEDA DI COMUNICAZIONE
//ID151 - RISERVATO (CONTATTARE PRODUTTORI)
//ID152 - ERRORE VERSIONE DI SICUREZZA
//ID153 - COMUNICAZIONE SCI (LATO CC) 
//ID154 - COMUNICAZIONE SCI (LATO AC) 
//ID155 - COMUNICAZIONE SCI (LATO COMBINATO CORRENTE CC)
//ID156 - VERSIONE SOFTWARE INCOERENTE
//ID157 - RISERVATO (CONTATTARE PRODUTTORI)
//ID161 - FORCESHUTDOWN
//ID162 - REMOTESHUTDOWN 
//ID163 - SPEGNIMENTO DRMS0
//ID165 - REMOTEDERATING 
//ID166 - DERATING INTERFACCIA LOGICA
//ID167 - DERATING ANTI-REFLUSSO
//ID169 - ALLARME VENTOLA 1
//ID170 - ALLARME VENTOLA 2
//ID171 - ALLARME VENTOLA 3
//ID172 - ALLARME VENTOLA 4
//ID173 - ALLARME VENTOLA 5
//ID174 - ALLARME VENTOLA 6
//ID177 - RISERVATO (CONTATTARE PRODUTTORI)
//ID178 - RISERVATO (CONTATTARE PRODUTTORI)
//ID179 - RISERVATO (CONTATTARE PRODUTTORI)
//ID180 - RISERVATO (CONTATTARE PRODUTTORI)
//ID181 - RISERVATO (CONTATTARE PRODUTTORI)
//ID182 - RISERVATO (CONTATTARE PRODUTTORI)


















