// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM2Si8yGQBmCk0iOkTCNnprOva2xATCBQ',
    appId: '1:797053733001:web:6fc51fd30c0fc8c783de58',
    messagingSenderId: '797053733001',
    projectId: 'romeo-energy-community',
    authDomain: 'romeo-energy-community.firebaseapp.com',
    storageBucket: 'romeo-energy-community.firebasestorage.app',
    measurementId: 'G-D708GM4816',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBebwZTUglV-jXENv6kykg1TFTh0ltkUjQ',
    appId: '1:797053733001:android:24e22f9e3471502583de58',
    messagingSenderId: '797053733001',
    projectId: 'romeo-energy-community',
    storageBucket: 'romeo-energy-community.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFw6ng7GgGDdj7YbRbCyAY44iofR2HZO8',
    appId: '1:797053733001:ios:191e7956f92b5b2883de58',
    messagingSenderId: '797053733001',
    projectId: 'romeo-energy-community',
    storageBucket: 'romeo-energy-community.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationRomeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFw6ng7GgGDdj7YbRbCyAY44iofR2HZO8',
    appId: '1:797053733001:ios:191e7956f92b5b2883de58',
    messagingSenderId: '797053733001',
    projectId: 'romeo-energy-community',
    storageBucket: 'romeo-energy-community.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationRomeo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM2Si8yGQBmCk0iOkTCNnprOva2xATCBQ',
    appId: '1:797053733001:web:ba8c832aa351c8ba83de58',
    messagingSenderId: '797053733001',
    projectId: 'romeo-energy-community',
    authDomain: 'romeo-energy-community.firebaseapp.com',
    storageBucket: 'romeo-energy-community.firebasestorage.app',
    measurementId: 'G-K6B2JFXHCL',
  );
}
